# Cross-compiling for iOS ARM64
SET(CMAKE_SYSTEM_NAME Darwin)
SET(CMAKE_SYSTEM_PROCESSOR arm64)

SET(CMAKE_OSX_ARCHITECTURES arm64)
SET(CMAKE_OSX_SYSROOT iphoneos)
SET(CMAKE_OSX_DEPLOYMENT_TARGET 11.0)

SET(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH YES)
